-- Tabelas SEM FK
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Brasil');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Argentina');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Uruguai');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Chile');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Paraguai');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Colômbia');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Peru');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('México');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Espanha');
INSERT INTO T_NIMBUS_PAIS (NM_PAIS) VALUES ('Portugal');

INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('São Paulo', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Minas Gerais', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Rio de Janeiro', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Bahia', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Paraná', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Santa Catarina', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Rio Grande do Sul', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Pernambuco', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Ceará', 1);
INSERT INTO T_NIMBUS_ESTADO (NM_ESTADO, ID_PAIS) VALUES ('Distrito Federal', 1);

INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('São Paulo', 1);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Campinas', 1);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Belo Horizonte', 2);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Rio de Janeiro', 3);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Salvador', 4);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Curitiba', 5);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Porto Alegre', 7);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Recife', 8);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Fortaleza', 9);
INSERT INTO T_NIMBUS_CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Brasília', 10);

INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-23.5505, -46.6333);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-22.9083, -43.1964);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-19.9167, -43.9333);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-12.9714, -38.5014);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-25.4284, -49.2733);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-30.0346, -51.2177);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-8.0579, -34.8813);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-3.7172, -38.5431);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-15.7942, -47.8825);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-22.9028, -47.0608);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-27.5969, -48.5495);
INSERT INTO T_NIMBUS_LOCALIZACAO(NR_LATITUDE, NR_LONGITUDE) VALUES (-1.4558, -48.5039);

INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Sé', 1, 1);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Copacabana', 4, 2);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Savassi', 3, 3);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Pelourinho', 5, 4);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Batel', 6, 5);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Moinhos de Vento', 7, 6);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Boa Viagem', 8, 7);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Meireles', 9, 8);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Asa Sul', 10, 9);
INSERT INTO T_NIMBUS_BAIRRO(NM_BAIRRO, ID_CIDADE, ID_LOCALIZACAO) VALUES ('Cambuí', 2, 10);

INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (1, '01001000', 'Praça da Sé', 100);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (2, '22070002', 'Av. Atlântica', 3000);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (3, '30130174', 'Rua Pernambuco', 1000);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (4, '40026010', 'Largo do Pelourinho', 50);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (5, '80420090', 'Av. do Batel', 1868);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (6, '90570020', 'Rua Padre Chagas', 300);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (7, '51020000', 'Av. Boa Viagem', 5000);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (8, '60165121', 'Av. Beira Mar', 3000);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (9, '70390100', 'SCS Quadra 7', 10);
INSERT INTO T_NIMBUS_ENDERECO (ID_BAIRRO, NR_CEP, NM_LOGRADOURO, NR_LOGRADOURO) VALUES (10, '13025150', 'Rua Maria Monteiro', 1200);

